$ANSIBLE_VAULT;1.1;AES256
36636166643464646563373237383632323864326437306438363761636461323966356465373730
3434646363616564356433303339323539643437313161310a353934306465653666663862303531
32393962623632323063666233356432633238646336303564613633636230353835313164353761
6663303237316232330a323561383661613839353739633234643031656361346133353363313634
61343537323531363561663261323631653732653465316632346631333462336236663264313133
37626334393862653532373837356638663235306231396632623231363734326466336430643965
62316530663534666238653837623334323235643366643530613566653136396530386131373739
37653264333935643031363632323930623165336134383064623962643864316166626233383136
35303732396431616432333061393866663562653332613663386532633934386636623538323735
61336137353032333162323865316337306161386364373965653564663739336465346135643134
33363036656563646539373734343466646230373065636231636230373061323335323231373761
36303634643038333639353161383665386363353033323030326662366133336361656532613139
3832
