$ANSIBLE_VAULT;1.1;AES256
35643432353631303562653363363836343765366238633161363437643733646662346365313632
6564373930636434666637393337383462623639663339380a353330653463346434323962316465
61643538346630643231316230616634316131396266393465343931353330393438643437623935
3064383966653732370a326365333265313862333761333466396162656433353036313939646165
38643236666639643037326330316264363632343536353632353334663761383835663961616665
39393835353833343836363830633433643365613362366565306663376464323638306461616536
61653062613231653534396166336332333661326639623631366435393132613336363233616261
64663639663136316237323036383230343266646533626364303566333435376164633364616236
6437
