---
# =============================================================================
# Ansible Inventory
# =============================================================================
# Actualiza las IPs según tu configuración
# =============================================================================

all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  children:
    # -------------------------------------------------------------------------
    # Proxmox VE Hosts
    # -------------------------------------------------------------------------
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.1.10
          # Variables específicas del PVE
          pve_enterprise_repo: false
          pve_no_subscription_repo: true
          # SSH keys to add to this host (optional)
          ssh_public_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCouRsnZwzAf/MQGTeopeu770tbNQDRK5bmkJw8IghKe3aqxSSjiYZunv28y64lc98HkRPrQM1FIcxrrmXllRtY6EQsfEVEoRpHrT+SoOdl8P/NNSrr7VtXUUQXDRal+zNh1xi+kAb90egBf7JWugBFwn4aHDhDbBGcpyC1bzkgYoOYj5iZoWOfISV2gQ4PJe8KSJa3NjmonBIFd+bC3FKCw2oJfs40/PyIVc6qLcVwjYzG86p+coKZ2aHfU8AxuwqYGqrTLrfxvgwH3p7a9oPZt26Fsqijh3kWiGtwHKJzd/am9Gfy6Wn13gcAlgIWs/yaCpK8Gu4mws8hAU5pfhucI0nY2IDZLKrjDBkWCi513XoQxa0sUZeGmD/O14bIzoMx2rM5HDKLbsvNNbs1WtDMZAWtszxlow78n5cwupfZjtXtCSyk4pKxQXKTn2Vl5XhDo/OYKrScIMJxjbfTUOyWrFIP0xpY0wWUCcOsP8K83l60SDP3e6++RZFfew5FmsU= sornor@litel"
          #   - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABA... user@desktop"

    # -------------------------------------------------------------------------
    # Control Plane LXC
    # -------------------------------------------------------------------------
    control_plane:
      hosts:
        control:
          ansible_host: 100.119.188.88  # control_plane

    # -------------------------------------------------------------------------
    # Future infrastructure hosts
    # -------------------------------------------------------------------------
    # gitlab:
    #   hosts:
    #     gitlab-server:
    #       ansible_host: 192.168.1.11
    #
    # homeassistant:
    #   hosts:
    #     ha:
    #       ansible_host: 192.168.1.20